"""empty message

Revision ID: 39899799a283
Revises: ff77c4a63065
Create Date: 2022-06-05 15:51:16.549498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39899799a283'
down_revision = 'ff77c4a63065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
